// Mocks generated by Mockito 5.4.6 from annotations
// in monitored_app/test/unit/services/emergency_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:monitored_app/core/database/database.dart' as _i2;
import 'package:monitored_app/core/services/database_service.dart' as _i3;
import 'package:monitored_app/core/services/notification_service.dart' as _i6;
import 'package:monitored_app/core/services/websocket_service.dart' as _i7;
import 'package:monitored_app/core/types/app_types.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeAppDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.AppDatabase);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> tryAcquireCollectionLease({
    required String? owner,
    required Duration? ttl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #tryAcquireCollectionLease,
          [],
          {
            #owner: owner,
            #ttl: ttl,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> touchCollectionLease(String? owner) => (super.noSuchMethod(
        Invocation.method(
          #touchCollectionLease,
          [owner],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> releaseCollectionLease(String? owner) => (super.noSuchMethod(
        Invocation.method(
          #releaseCollectionLease,
          [owner],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String?> getCollectionLeaseOwner() => (super.noSuchMethod(
        Invocation.method(
          #getCollectionLeaseOwner,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> queueDataForSync(
    String? dataType,
    Map<String, dynamic>? data, {
    int? priority = 2,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queueDataForSync,
          [
            dataType,
            data,
          ],
          {#priority: priority},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setDataNotificationCallback(
          dynamic Function(
            String,
            Map<String, dynamic>,
          )? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #setDataNotificationCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> insertSmsData({
    required String? deviceId,
    required String? messageType,
    required String? direction,
    required String? sender,
    String? senderName,
    required String? body,
    required DateTime? sentAt,
    String? conversationId,
    bool? hasAttachment = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSmsData,
          [],
          {
            #deviceId: deviceId,
            #messageType: messageType,
            #direction: direction,
            #sender: sender,
            #senderName: senderName,
            #body: body,
            #sentAt: sentAt,
            #conversationId: conversationId,
            #hasAttachment: hasAttachment,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertCallData({
    required String? deviceId,
    required String? callType,
    required String? phoneNumber,
    String? contactName,
    required DateTime? startTime,
    DateTime? endTime,
    int? duration = 0,
    bool? isVideoCall = false,
    int? simSlot,
    bool? isConference = false,
    DateTime? recordedAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertCallData,
          [],
          {
            #deviceId: deviceId,
            #callType: callType,
            #phoneNumber: phoneNumber,
            #contactName: contactName,
            #startTime: startTime,
            #endTime: endTime,
            #duration: duration,
            #isVideoCall: isVideoCall,
            #simSlot: simSlot,
            #isConference: isConference,
            #recordedAt: recordedAt,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertLocationData({
    required String? deviceId,
    required double? latitude,
    required double? longitude,
    required double? accuracy,
    double? altitude,
    double? speed,
    double? bearing,
    double? heading,
    required String? provider,
    String? activityType,
    int? batteryLevel,
    DateTime? recordedAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertLocationData,
          [],
          {
            #deviceId: deviceId,
            #latitude: latitude,
            #longitude: longitude,
            #accuracy: accuracy,
            #altitude: altitude,
            #speed: speed,
            #bearing: bearing,
            #heading: heading,
            #provider: provider,
            #activityType: activityType,
            #batteryLevel: batteryLevel,
            #recordedAt: recordedAt,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertAppUsageData({
    required String? deviceId,
    required String? packageName,
    String? appName,
    required DateTime? startTime,
    required DateTime? endTime,
    required int? duration,
    required String? date,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAppUsageData,
          [],
          {
            #deviceId: deviceId,
            #packageName: packageName,
            #appName: appName,
            #startTime: startTime,
            #endTime: endTime,
            #duration: duration,
            #date: date,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertAppData({
    required String? deviceId,
    required String? packageName,
    required String? appName,
    String? versionName,
    int? versionCode,
    required DateTime? firstInstallTime,
    DateTime? lastUpdateTime,
    String? appCategory,
    required bool? isSystemApp,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAppData,
          [],
          {
            #deviceId: deviceId,
            #packageName: packageName,
            #appName: appName,
            #versionName: versionName,
            #versionCode: versionCode,
            #firstInstallTime: firstInstallTime,
            #lastUpdateTime: lastUpdateTime,
            #appCategory: appCategory,
            #isSystemApp: isSystemApp,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertMediaData({
    required String? deviceId,
    required String? mediaId,
    required String? filePath,
    required String? fileName,
    required int? fileSize,
    required String? mimeType,
    required String? mediaType,
    required DateTime? createdAt,
    int? width,
    int? height,
    String? cameraType,
    int? duration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMediaData,
          [],
          {
            #deviceId: deviceId,
            #mediaId: mediaId,
            #filePath: filePath,
            #fileName: fileName,
            #fileSize: fileSize,
            #mimeType: mimeType,
            #mediaType: mediaType,
            #createdAt: createdAt,
            #width: width,
            #height: height,
            #cameraType: cameraType,
            #duration: duration,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setConfiguration(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setConfiguration,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getConfiguration(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getConfiguration,
          [key],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> logSecurityEvent({
    required String? eventType,
    required String? description,
    required String? severity,
    String? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logSecurityEvent,
          [],
          {
            #eventType: eventType,
            #description: description,
            #severity: severity,
            #metadata: metadata,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.SyncQueueTableData>> getPendingSyncItems(
          {int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSyncItems,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i2.SyncQueueTableData>>.value(
            <_i2.SyncQueueTableData>[]),
      ) as _i4.Future<List<_i2.SyncQueueTableData>>);

  @override
  _i4.Future<void> markSyncItemCompleted(int? syncId) => (super.noSuchMethod(
        Invocation.method(
          #markSyncItemCompleted,
          [syncId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markSyncItemFailed(int? syncId) => (super.noSuchMethod(
        Invocation.method(
          #markSyncItemFailed,
          [syncId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateSyncItemStatus(
    int? syncId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSyncItemStatus,
          [
            syncId,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadPendingDataToCollector() => (super.noSuchMethod(
        Invocation.method(
          #loadPendingDataToCollector,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markItemsSynced(List<Map<String, dynamic>>? syncedItems) =>
      (super.noSuchMethod(
        Invocation.method(
          #markItemsSynced,
          [syncedItems],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markItemsPermanentlyFailed(
          List<Map<String, dynamic>>? failedItems) =>
      (super.noSuchMethod(
        Invocation.method(
          #markItemsPermanentlyFailed,
          [failedItems],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, int>> getSyncQueueStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getSyncQueueStatistics,
          [],
        ),
        returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i4.Future<Map<String, int>>);

  @override
  _i4.Future<void> cleanupOldSyncItems() => (super.noSuchMethod(
        Invocation.method(
          #cleanupOldSyncItems,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> performMaintenance() => (super.noSuchMethod(
        Invocation.method(
          #performMaintenance,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, int>> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i4.Future<Map<String, int>>);

  @override
  _i4.Future<void> clearSensitiveData() => (super.noSuchMethod(
        Invocation.method(
          #clearSensitiveData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> forceSyncAllPendingData() => (super.noSuchMethod(
        Invocation.method(
          #forceSyncAllPendingData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertCommandExecutionResult(dynamic result) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertCommandExecutionResult,
          [result],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertSecurityAuditEvent({
    required String? eventType,
    required String? description,
    required String? severity,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSecurityAuditEvent,
          [],
          {
            #eventType: eventType,
            #description: description,
            #severity: severity,
            #metadata: metadata,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertPerformanceMetrics(
          List<_i5.PerformanceMetric>? metrics) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPerformanceMetrics,
          [metrics],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<dynamic>> getPerformanceMetrics(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPerformanceMetrics,
          [
            start,
            end,
          ],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<List<dynamic>> getConsentRecords() => (super.noSuchMethod(
        Invocation.method(
          #getConsentRecords,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<void> insertConsentRecord(_i5.ConsentRecord? consent) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertConsentRecord,
          [consent],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateConsentRecord(_i5.ConsentRecord? consent) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConsentRecord,
          [consent],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteOldDataByCategory(
    _i5.DataCategory? category,
    DateTime? cutoffDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOldDataByCategory,
          [
            category,
            cutoffDate,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllDataByCategory(_i5.DataCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAllDataByCategory,
          [category],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertEmergencyEvent(dynamic emergencyEvent) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertEmergencyEvent,
          [emergencyEvent],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateEmergencyEvent(dynamic emergencyEvent) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEmergencyEvent,
          [emergencyEvent],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getEmergencyEvents({int? limit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmergencyEvents,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> getMediaAnalytics({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMediaAnalytics,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> logTamperAttempt(
    String? tamperType,
    String? details,
    String? severity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logTamperAttempt,
          [
            tamperType,
            details,
            severity,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveFileTransferSession(Map<String, dynamic>? sessionData) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFileTransferSession,
          [sessionData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getPendingFileTransfers() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingFileTransfers,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> removeFileTransferSession(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFileTransferSession,
          [sessionId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> storeSecurityBaseline(Map<String, dynamic>? baseline) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeSecurityBaseline,
          [baseline],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.SyncQueueTableData>> getSyncItemsByTypeAndStatus(
    String? type,
    List<String>? statuses,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncItemsByTypeAndStatus,
          [
            type,
            statuses,
          ],
        ),
        returnValue: _i4.Future<List<_i2.SyncQueueTableData>>.value(
            <_i2.SyncQueueTableData>[]),
      ) as _i4.Future<List<_i2.SyncQueueTableData>>);

  @override
  _i4.Future<List<_i2.SyncQueueTableData>> getSyncItemsByType(String? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncItemsByType,
          [type],
        ),
        returnValue: _i4.Future<List<_i2.SyncQueueTableData>>.value(
            <_i2.SyncQueueTableData>[]),
      ) as _i4.Future<List<_i2.SyncQueueTableData>>);

  @override
  _i4.Future<void> deleteSyncItemsByType(String? type) => (super.noSuchMethod(
        Invocation.method(
          #deleteSyncItemsByType,
          [type],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getSyncQueueSize() => (super.noSuchMethod(
        Invocation.method(
          #getSyncQueueSize,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> prioritizeSyncQueue() => (super.noSuchMethod(
        Invocation.method(
          #prioritizeSyncQueue,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i6.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> setupPushNotifications() => (super.noSuchMethod(
        Invocation.method(
          #setupPushNotifications,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> registerFcmToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #registerFcmToken,
          [token],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showEmergencyNotification(
    String? title,
    String? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showEmergencyNotification,
          [
            title,
            body,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> hideEmergencyNotification() => (super.noSuchMethod(
        Invocation.method(
          #hideEmergencyNotification,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showNotification(
    String? title,
    String? body, {
    String? channel = 'default_channel',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showNotification,
          [
            title,
            body,
          ],
          {#channel: channel},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> showTamperAlert(
    String? tamperType,
    String? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #showTamperAlert,
          [
            tamperType,
            details,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [WebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketService extends _i1.Mock implements _i7.WebSocketService {
  MockWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void sendStatusUpdate({
    required int? batteryLevel,
    required bool? isCharging,
    Map<String, dynamic>? securityStatus,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #sendStatusUpdate,
          [],
          {
            #batteryLevel: batteryLevel,
            #isCharging: isCharging,
            #securityStatus: securityStatus,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendSecurityAlert({
    required String? alertType,
    required String? description,
    required String? severity,
    Map<String, dynamic>? metadata,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #sendSecurityAlert,
          [],
          {
            #alertType: alertType,
            #description: description,
            #severity: severity,
            #metadata: metadata,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setP2PSignalingCallback(
          dynamic Function(Map<String, dynamic>)? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #setP2PSignalingCallback,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addMessageHandler(
    String? messageType,
    dynamic Function(Map<String, dynamic>)? handler,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addMessageHandler,
          [
            messageType,
            handler,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeMessageHandler(String? messageType) => super.noSuchMethod(
        Invocation.method(
          #removeMessageHandler,
          [messageType],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<bool> sendMessage(Map<String, dynamic>? message) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [message],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void sendP2PSignalingMessage(Map<String, dynamic>? signalingData) =>
      super.noSuchMethod(
        Invocation.method(
          #sendP2PSignalingMessage,
          [signalingData],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void requestP2PConnection(
    String? targetDeviceId,
    Map<String, dynamic>? metadata,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #requestP2PConnection,
          [
            targetDeviceId,
            metadata,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyP2PConnectionStatus(
    String? peerId,
    String? status,
    Map<String, dynamic>? details,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #notifyP2PConnectionStatus,
          [
            peerId,
            status,
            details,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> sendEmergencyAlert(Map<String, dynamic>? emergencyData) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmergencyAlert,
          [emergencyData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendEmergencyHeartbeat(
          Map<String, dynamic>? heartbeatData) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmergencyHeartbeat,
          [heartbeatData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendEmergencyDeactivation(
          Map<String, dynamic>? deactivationData) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmergencyDeactivation,
          [deactivationData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendEmergencyMessage(Map<String, dynamic>? messageData) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmergencyMessage,
          [messageData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendStreamFrame(
    List<int>? frameData,
    Map<String, dynamic>? metadata,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendStreamFrame,
          [
            frameData,
            metadata,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendStreamBuffer(
    List<int>? bufferData,
    String? streamType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendStreamBuffer,
          [
            bufferData,
            streamType,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendMediaData(Map<String, dynamic>? mediaData) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMediaData,
          [mediaData],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendMediaAlert(
    String? alertType,
    Map<String, dynamic>? alertData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMediaAlert,
          [
            alertType,
            alertData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
