// Mocks generated by Mockito 5.4.6 from annotations
// in monitored_app/test/widget/emergency_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:monitored_app/core/services/emergency_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EmergencyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmergencyService extends _i1.Mock implements _i2.EmergencyService {
  MockEmergencyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i2.EmergencyState> get stateStream => (super.noSuchMethod(
        Invocation.getter(#stateStream),
        returnValue: _i3.Stream<_i2.EmergencyState>.empty(),
      ) as _i3.Stream<_i2.EmergencyState>);

  @override
  _i3.Stream<_i2.EmergencyEvent> get eventStream => (super.noSuchMethod(
        Invocation.getter(#eventStream),
        returnValue: _i3.Stream<_i2.EmergencyEvent>.empty(),
      ) as _i3.Stream<_i2.EmergencyEvent>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i2.EmergencyState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _i2.EmergencyState.inactive,
      ) as _i2.EmergencyState);

  @override
  bool get isEmergencyActive => (super.noSuchMethod(
        Invocation.getter(#isEmergencyActive),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> activateEmergency({
    _i2.EmergencyTriggerType? triggerType = _i2.EmergencyTriggerType.manual,
    _i2.EmergencyTrigger? trigger = _i2.EmergencyTrigger.sosButton,
    _i2.EmergencyPriority? priority = _i2.EmergencyPriority.high,
    Map<String, dynamic>? triggerData,
    Duration? duration,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #activateEmergency,
          [],
          {
            #triggerType: triggerType,
            #trigger: trigger,
            #priority: priority,
            #triggerData: triggerData,
            #duration: duration,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deactivateEmergency() => (super.noSuchMethod(
        Invocation.method(
          #deactivateEmergency,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String?> captureEmergencyPhoto({bool? frontCamera = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #captureEmergencyPhoto,
          [],
          {#frontCamera: frontCamera},
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> recordEmergencyAudio({int? durationSeconds = 30}) =>
      (super.noSuchMethod(
        Invocation.method(
          #recordEmergencyAudio,
          [],
          {#durationSeconds: durationSeconds},
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<bool> sendEmergencyMessage(String? message) => (super.noSuchMethod(
        Invocation.method(
          #sendEmergencyMessage,
          [message],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> updateConfiguration({
    bool? autoLocationTracking,
    bool? autoMediaCapture,
    bool? autoNotifyContacts,
    int? emergencyDataSyncInterval,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateConfiguration,
          [],
          {
            #autoLocationTracking: autoLocationTracking,
            #autoMediaCapture: autoMediaCapture,
            #autoNotifyContacts: autoNotifyContacts,
            #emergencyDataSyncInterval: emergencyDataSyncInterval,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  Map<String, dynamic> getConfiguration() => (super.noSuchMethod(
        Invocation.method(
          #getConfiguration,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i3.Future<void> setupPanicButton() => (super.noSuchMethod(
        Invocation.method(
          #setupPanicButton,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setupShakeDetection() => (super.noSuchMethod(
        Invocation.method(
          #setupShakeDetection,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setupVoiceKeywordDetection() => (super.noSuchMethod(
        Invocation.method(
          #setupVoiceKeywordDetection,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setupGeofenceMonitoring(
          List<Map<String, dynamic>>? geofences) =>
      (super.noSuchMethod(
        Invocation.method(
          #setupGeofenceMonitoring,
          [geofences],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getEmergencyStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmergencyStatistics,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<bool> testEmergencySystem() => (super.noSuchMethod(
        Invocation.method(
          #testEmergencySystem,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
